source/api_v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api_v1.views import CompanyViewSet

app_name = 'api_v1'

router = DefaultRouter()
router.register(r'company', CompanyViewSet)


urlpatterns = [
    path('', include(router.urls))
]

source/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api-v1/', include('api_v1.urls')),
]

source/webapp/urls.py
from django.urls import path

from webapp.views import CompanyData, TaskView, SaveInDataBase, GetFiles

app_name = 'webapp'

urlpatterns = [
    path('', CompanyData.as_view(), name='data'),
    path('get-files/', GetFiles.as_view(), name='get_files'),
    path('save-in-base/', SaveInDataBase.as_view(), name='Save_in_base'),
    path('task/<str:task_id>/', TaskView.as_view(), name='task'),
 ]

source/api_v1/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Company(models.Model):
    name = models.CharField(max_length=32, verbose_name=_("Company"))

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = _('Company')
        verbose_name_plural = _('Companies')


class Data(models.Model):
    company = models.ForeignKey('webapp.Company', related_name=_("data"), on_delete=models.CASCADE,
                                verbose_name=_("company"))
    date = models.DateField(verbose_name=_("Date"))
    open = models.DecimalField(verbose_name=_("Open"), max_digits=10, decimal_places=6)
    high = models.DecimalField(verbose_name=_("High"), max_digits=10, decimal_places=6)
    low = models.DecimalField(verbose_name=_("Low"), max_digits=10, decimal_places=6)
    close = models.DecimalField(verbose_name=_("Close"), max_digits=10, decimal_places=6)
    adj_close = models.DecimalField(verbose_name=_("Adj Close"), max_digits=10, decimal_places=6)
    volume = models.IntegerField(verbose_name=_("Volume"))

    def __str__(self):
        return f'{self.date}'

    class Meta:
        verbose_name = _('Data')
        verbose_name_plural = _('Data')

source/api_v1/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import get_object_or_404
from rest_framework.response import Response
from rest_framework.viewsets import ViewSet

from api_v1.serializers import CompanySerializer
from webapp.models import Company


class CompanyViewSet(ViewSet):
    queryset = Company.objects.all()

    def list(self, request):
        objects = Company.objects.all()
        slr = CompanySerializer(objects, many=True, context={'request': request})
        return Response(slr.data)

    def retrieve(self, request, pk=None):
        article = get_object_or_404(Company, pk=pk)
        slr = CompanySerializer(article, context={'request': request})
        return Response(slr.data)

source/webapp/views.py
from celery import current_app
from django.http import JsonResponse
from django.shortcuts import render
from django.views.generic.base import View

from webapp.tasks import parse_all_files, get_company_data, DIR
from webapp.utils import get_companies_data, get_files


class CompanyData(View):
    def get(self, *args, **kwargs):
        context = {
            'company': get_companies_data(),
            'files': get_files(DIR)
        }
        return render(self.request, 'index.html', context=context)


class GetFiles(View):
    def get(self, *args, **kwargs):
        context = {'head': "Scraping data from sites"}
        task = get_company_data.delay()
        context['task_id'] = task.id
        return render(self.request, 'task_result.html', context=context)


class SaveInDataBase(View):
    def get(self, *args, **kwargs):
        context = {'head': "Saving data from file into db"}
        task = parse_all_files.delay()
        context['task_id'] = task.id
        return render(self.request, 'task_result.html', context=context)


class TaskView(View):
    def get(self, request, task_id):
        task = current_app.AsyncResult(task_id)
        response_data = {'task_status': task.status, 'task_id': task.id}
        return JsonResponse(response_data)

source/webapp/templates/base.html
{% load i18n %}
{% load static %}
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>{% block title %}Mega{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body class="d-flex flex-column h-100">

    <header>
      <nav class="navbar navbar-expand-md navbar-dark fixed-top" style="background-color: #452b92">
        <div class="container">
        <a class="navbar-brand" href="/">{% trans "Main page" %}</a>
        </div>
      </nav>
    </header>

    <div class="container pt-3">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="footer fixed-bottom"  style="background-color: #452b92; color: white">
        <div class="footer-copyright text-center py-3">
            <script>
                document.write("Copyright &copy; "+ new Date().getFullYear());
            </script>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="mb-3 row gx-2 justify-content-evenly">
    <div class="col-auto  md-auto">
       <h6>Loaded files: </h6><br>
        {% if files %}
            {% for file in files %}
                <span> <b>{{ file }}</b></span><br>
            {% endfor %}
        {% else %}
            0.
        {% endif %}
        <br>
        <a href="{% url 'webapp:get_files' %}">
            <button class="btn btn-lg" style="background-color: #72c042">{% trans "Start Scraping" %}</button>
        </a>
    </div>
    <div class="col-auto  md-auto">
        <h6>Companies  in the database: </h6><br>
        {% if company %}
            {% for name, data in company.items %}
                <span> <b>{{ name }}</b>  -  {{ data }} records.</span><br>
            {% endfor %}
        {% else %}
            0.
        {% endif %}
        <br>
        <a href="{% url 'webapp:Save_in_base' %}">
            <button class="btn btn-lg" style="background-color: #72c042">{% trans "Save Data in db" %}</button>
        </a>
    </div>
</div>

{% endblock %}

source/webapp/templates/task_result.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="text-center">
    <h3>{{ head }}</h3>
    <span><span class="text-center" id="progress-title"></span></span><span id="dot"></span>
    <div style="display: none"><a id="task_url" href="{% url 'webapp:task' task_id=task_id %}"></a></div>
    <h3 id="status"> </h3>
</div>

{% if task_id %}
    <script type="application/javascript" src="{% static 'js/message_task_check_state.js' %}"></script>
{% endif %}

{% endblock %}